[package]
name = "vetis-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
deboa = "0.0.9"
http = "1.4.0"
http-body-util = "0.1.3"
tokio = "1.49.0"
vetis = { version = "0.1.3", path = "../vetis" }
